language: python
python:
  - 3.4
  - 3.5
env:
  - TOXENV=py34
  - TOXENV=py35
os:
  - linux
install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
